import { db, opportunitiesTable } from "@workspace/db";

const past = [
  {
    title: "Dubai Fight Night",
    country: "UAE", city: "Dubai", sport: "Boxing",
    weightClass: "Welterweight", level: "Professional",
    purse: "€7,500", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Professional welterweight boxing bout held in Dubai. IFA sanctioned event with full travel and accommodation covered.",
    location: "Dubai, UAE", type: "fight",
  },
  {
    title: "Riyadh Heavyweight Showcase",
    country: "Saudi Arabia", city: "Riyadh", sport: "Boxing",
    weightClass: "Heavyweight", level: "Professional",
    purse: "€50,000", travelIncluded: true, accommodationIncluded: true,
    status: "closed",
    description: "High-profile heavyweight showcase in Riyadh. One of the biggest purses on the IFA circuit this year.",
    location: "Riyadh, Saudi Arabia", type: "fight",
  },
  {
    title: "London Prospect Series",
    country: "United Kingdom", city: "London", sport: "Boxing",
    weightClass: "Lightweight", level: "Professional",
    purse: "€5,000", travelIncluded: false, accommodationIncluded: true,
    status: "completed",
    description: "Lightweight prospect series in London. Accommodation provided. Strong exposure opportunity on the UK circuit.",
    location: "London, United Kingdom", type: "fight",
  },
  {
    title: "Madrid Boxing Night",
    country: "Spain", city: "Madrid", sport: "Boxing",
    weightClass: "Super Lightweight", level: "Professional",
    purse: "€6,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Super lightweight boxing card in Madrid. Full travel and accommodation package. IFA verified event.",
    location: "Madrid, Spain", type: "fight",
  },
  {
    title: "Manchester Cruiserweight Card",
    country: "United Kingdom", city: "Manchester", sport: "Boxing",
    weightClass: "Cruiserweight", level: "Professional",
    purse: "€12,000", travelIncluded: true, accommodationIncluded: true,
    status: "closed",
    description: "Cruiserweight professional card at a premier Manchester venue. Full logistics support included.",
    location: "Manchester, United Kingdom", type: "fight",
  },
  {
    title: "Mexico City Contender Event",
    country: "Mexico", city: "Mexico City", sport: "Boxing",
    weightClass: "Featherweight", level: "Professional",
    purse: "€8,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Featherweight contender event in Mexico City. High-energy crowd and broadcast coverage.",
    location: "Mexico City, Mexico", type: "fight",
  },
  {
    title: "Miami Fight Series",
    country: "USA", city: "Miami", sport: "Boxing",
    weightClass: "Middleweight", level: "Professional",
    purse: "€10,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Middleweight professional series in Miami. Broadcast-ready event with media coverage for all participants.",
    location: "Miami, USA", type: "fight",
  },
  {
    title: "Tokyo Super Bantamweight Card",
    country: "Japan", city: "Tokyo", sport: "Boxing",
    weightClass: "Super Bantamweight", level: "Professional",
    purse: "€15,000", travelIncluded: true, accommodationIncluded: true,
    status: "closed",
    description: "Super bantamweight professional card in Tokyo. Premium production and Asian market exposure.",
    location: "Tokyo, Japan", type: "fight",
  },
  {
    title: "Bangkok Muay Thai Showcase",
    country: "Thailand", city: "Bangkok", sport: "Muay Thai",
    weightClass: "Lightweight", level: "Professional",
    purse: "€4,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Professional Muay Thai showcase in Bangkok. Authentic venue with international broadcast reach.",
    location: "Bangkok, Thailand", type: "fight",
  },
  {
    title: "Las Vegas Prospect Card",
    country: "USA", city: "Las Vegas", sport: "Boxing",
    weightClass: "Lightweight", level: "Professional",
    purse: "€18,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Lightweight prospect card in Las Vegas. Premium venue with media and streaming distribution.",
    location: "Las Vegas, USA", type: "fight",
  },
  {
    title: "Paris International Boxing Event",
    country: "France", city: "Paris", sport: "Boxing",
    weightClass: "Welterweight", level: "Professional",
    purse: "€9,500", travelIncluded: true, accommodationIncluded: true,
    status: "closed",
    description: "International welterweight boxing event in Paris. IFA certified with full travel logistics.",
    location: "Paris, France", type: "fight",
  },
  {
    title: "Milan Fight Night",
    country: "Italy", city: "Milan", sport: "Boxing",
    weightClass: "Middleweight", level: "Professional",
    purse: "€7,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Middleweight professional fight night in Milan. European circuit showcase with IFA sanctioning.",
    location: "Milan, Italy", type: "fight",
  },
  {
    title: "Berlin Combat Sports Card",
    country: "Germany", city: "Berlin", sport: "Kickboxing",
    weightClass: "Light Heavyweight", level: "Professional",
    purse: "€6,500", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Light heavyweight kickboxing card in Berlin. Strong European audience and live broadcast.",
    location: "Berlin, Germany", type: "fight",
  },
  {
    title: "Istanbul Boxing Showcase",
    country: "Turkey", city: "Istanbul", sport: "Boxing",
    weightClass: "Heavyweight", level: "Professional",
    purse: "€20,000", travelIncluded: true, accommodationIncluded: true,
    status: "closed",
    description: "Heavyweight boxing showcase in Istanbul. Bridge between European and Middle Eastern markets.",
    location: "Istanbul, Turkey", type: "fight",
  },
  {
    title: "Abu Dhabi International Fight Card",
    country: "UAE", city: "Abu Dhabi", sport: "Boxing",
    weightClass: "Super Welterweight", level: "Professional",
    purse: "€25,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Super welterweight international fight card in Abu Dhabi. Premium event with VIP audience.",
    location: "Abu Dhabi, UAE", type: "fight",
  },
  {
    title: "São Paulo Fight Night",
    country: "Brazil", city: "São Paulo", sport: "Boxing",
    weightClass: "Lightweight", level: "Professional",
    purse: "€5,500", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Lightweight boxing night in São Paulo. Latin America's premier IFA event of the season.",
    location: "São Paulo, Brazil", type: "fight",
  },
  {
    title: "Buenos Aires Boxing Event",
    country: "Argentina", city: "Buenos Aires", sport: "Boxing",
    weightClass: "Featherweight", level: "Professional",
    purse: "€4,500", travelIncluded: true, accommodationIncluded: true,
    status: "closed",
    description: "Featherweight boxing event in Buenos Aires. Passionate crowd and national TV coverage.",
    location: "Buenos Aires, Argentina", type: "fight",
  },
  {
    title: "Doha Boxing Showcase",
    country: "Qatar", city: "Doha", sport: "Boxing",
    weightClass: "Cruiserweight", level: "Professional",
    purse: "€30,000", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Cruiserweight boxing showcase in Doha. High-profile Gulf region event with premium hospitality.",
    location: "Doha, Qatar", type: "fight",
  },
  {
    title: "Amsterdam Kickboxing Event",
    country: "Netherlands", city: "Amsterdam", sport: "Kickboxing",
    weightClass: "Middleweight", level: "Professional",
    purse: "€8,500", travelIncluded: true, accommodationIncluded: true,
    status: "completed",
    description: "Middleweight kickboxing event in Amsterdam. Strong European kickboxing fanbase and media.",
    location: "Amsterdam, Netherlands", type: "fight",
  },
  {
    title: "Gibraltar Fight Night",
    country: "Gibraltar", city: "Gibraltar", sport: "Boxing",
    weightClass: "Welterweight", level: "Professional",
    purse: "€6,000", travelIncluded: true, accommodationIncluded: true,
    status: "closed",
    description: "Welterweight boxing night in Gibraltar. Unique Mediterranean venue with international reach.",
    location: "Gibraltar, Gibraltar", type: "fight",
  },
];

const upcoming = [
  {
    title: "Dubai International Showcase",
    country: "UAE", city: "Dubai", sport: "Boxing",
    weightClass: "Welterweight", level: "Professional",
    purse: "€35,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Welterweight professional boxing showcase in Dubai. IFA members get priority access. Full travel and accommodation included.",
    location: "Dubai, UAE", type: "fight",
  },
  {
    title: "Riyadh Heavyweight Opportunity",
    country: "Saudi Arabia", city: "Riyadh", sport: "Boxing",
    weightClass: "Heavyweight", level: "Professional",
    purse: "€75,000", travelIncluded: true, accommodationIncluded: true,
    status: "recruiting",
    description: "Major heavyweight opportunity in Riyadh. One of the highest-purse openings on the IFA circuit. IFA is actively recruiting.",
    location: "Riyadh, Saudi Arabia", type: "fight",
  },
  {
    title: "Madrid Elite Boxing Event",
    country: "Spain", city: "Madrid", sport: "Boxing",
    weightClass: "Lightweight", level: "Professional",
    purse: "€8,500", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Elite lightweight boxing event in Madrid. Apply now for this European circuit opportunity.",
    location: "Madrid, Spain", type: "fight",
  },
  {
    title: "London International Fight Card",
    country: "United Kingdom", city: "London", sport: "Boxing",
    weightClass: "Middleweight", level: "Professional",
    purse: "€18,000", travelIncluded: true, accommodationIncluded: true,
    status: "scouting",
    description: "Middleweight international fight card in London. IFA is scouting registered fighters at this weight class.",
    location: "London, United Kingdom", type: "fight",
  },
  {
    title: "Manchester Arena Prospect Card",
    country: "United Kingdom", city: "Manchester", sport: "Boxing",
    weightClass: "Super Lightweight", level: "Professional",
    purse: "€12,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Super lightweight prospect card in Manchester. Opportunity for rising talent to compete at a premier UK arena.",
    location: "Manchester, United Kingdom", type: "fight",
  },
  {
    title: "Tokyo Lightweight Scouting Opportunity",
    country: "Japan", city: "Tokyo", sport: "Boxing",
    weightClass: "Lightweight", level: "Professional",
    purse: "€12,000", travelIncluded: true, accommodationIncluded: true,
    status: "scouting",
    description: "Lightweight scouting opportunity in Tokyo. IFA is identifying fighters for this Japanese market event.",
    location: "Tokyo, Japan", type: "fight",
  },
  {
    title: "Miami Prospect Card",
    country: "USA", city: "Miami", sport: "Boxing",
    weightClass: "Featherweight", level: "Professional",
    purse: "€4,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Featherweight prospect card in Miami. Build your record in one of North America's top boxing markets.",
    location: "Miami, USA", type: "fight",
  },
  {
    title: "Las Vegas International Boxing Slot",
    country: "USA", city: "Las Vegas", sport: "Boxing",
    weightClass: "Super Featherweight", level: "Professional",
    purse: "€25,000", travelIncluded: true, accommodationIncluded: true,
    status: "expected",
    description: "Super featherweight slot at a Las Vegas international boxing event. Expected to open for IFA member applications.",
    location: "Las Vegas, USA", type: "fight",
  },
  {
    title: "Mexico City Contender Slot",
    country: "Mexico", city: "Mexico City", sport: "Boxing",
    weightClass: "Bantamweight", level: "Professional",
    purse: "€7,500", travelIncluded: true, accommodationIncluded: true,
    status: "recruiting",
    description: "Bantamweight contender slot in Mexico City. IFA is actively recruiting fighters in this division.",
    location: "Mexico City, Mexico", type: "fight",
  },
  {
    title: "Abu Dhabi Fight Opportunity",
    country: "UAE", city: "Abu Dhabi", sport: "Boxing",
    weightClass: "Light Heavyweight", level: "Professional",
    purse: "€40,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Light heavyweight fight opportunity in Abu Dhabi. Premium Gulf event open to IFA registered fighters.",
    location: "Abu Dhabi, UAE", type: "fight",
  },
  {
    title: "Doha Cruiserweight Showcase",
    country: "Qatar", city: "Doha", sport: "Boxing",
    weightClass: "Cruiserweight", level: "Professional",
    purse: "€45,000", travelIncluded: true, accommodationIncluded: true,
    status: "expected",
    description: "Cruiserweight showcase in Doha. Expected opening for elite IFA fighters. High-profile Gulf region event.",
    location: "Doha, Qatar", type: "fight",
  },
  {
    title: "Bangkok Muay Thai Opportunity",
    country: "Thailand", city: "Bangkok", sport: "Muay Thai",
    weightClass: "Lightweight", level: "Professional",
    purse: "€5,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Professional Muay Thai opportunity in Bangkok. Authentic venue with international streaming coverage.",
    location: "Bangkok, Thailand", type: "fight",
  },
  {
    title: "Paris Boxing Showcase",
    country: "France", city: "Paris", sport: "Boxing",
    weightClass: "Welterweight", level: "Professional",
    purse: "€11,000", travelIncluded: true, accommodationIncluded: true,
    status: "scouting",
    description: "Welterweight boxing showcase in Paris. IFA is scouting for this high-profile European event.",
    location: "Paris, France", type: "fight",
  },
  {
    title: "Milan Super Welterweight Card",
    country: "Italy", city: "Milan", sport: "Boxing",
    weightClass: "Super Welterweight", level: "Professional",
    purse: "€9,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Super welterweight professional card in Milan. European circuit event with broadcast coverage.",
    location: "Milan, Italy", type: "fight",
  },
  {
    title: "Berlin Kickboxing Card",
    country: "Germany", city: "Berlin", sport: "Kickboxing",
    weightClass: "Middleweight", level: "Professional",
    purse: "€7,500", travelIncluded: true, accommodationIncluded: true,
    status: "recruiting",
    description: "Middleweight kickboxing card in Berlin. IFA is recruiting fighters for this strong European market event.",
    location: "Berlin, Germany", type: "fight",
  },
  {
    title: "Istanbul Heavyweight Slot",
    country: "Turkey", city: "Istanbul", sport: "Boxing",
    weightClass: "Heavyweight", level: "Professional",
    purse: "€22,000", travelIncluded: true, accommodationIncluded: true,
    status: "expected",
    description: "Heavyweight slot at an Istanbul boxing event. Expected to be confirmed for IFA members shortly.",
    location: "Istanbul, Turkey", type: "fight",
  },
  {
    title: "São Paulo Boxing Opportunity",
    country: "Brazil", city: "São Paulo", sport: "Boxing",
    weightClass: "Lightweight", level: "Professional",
    purse: "€6,500", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Lightweight boxing opportunity in São Paulo. Latin America's most active IFA market.",
    location: "São Paulo, Brazil", type: "fight",
  },
  {
    title: "Buenos Aires Featherweight Card",
    country: "Argentina", city: "Buenos Aires", sport: "Boxing",
    weightClass: "Featherweight", level: "Professional",
    purse: "€5,000", travelIncluded: true, accommodationIncluded: true,
    status: "scouting",
    description: "Featherweight card in Buenos Aires. IFA is scouting fighters for this Latin American event.",
    location: "Buenos Aires, Argentina", type: "fight",
  },
  {
    title: "Amsterdam Middleweight Opportunity",
    country: "Netherlands", city: "Amsterdam", sport: "Kickboxing",
    weightClass: "Middleweight", level: "Professional",
    purse: "€8,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Middleweight kickboxing opportunity in Amsterdam. Strong European audience and live event production.",
    location: "Amsterdam, Netherlands", type: "fight",
  },
  {
    title: "Gibraltar Boxing Event",
    country: "Gibraltar", city: "Gibraltar", sport: "Boxing",
    weightClass: "Welterweight", level: "Professional",
    purse: "€7,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Welterweight boxing event in Gibraltar. Unique Mediterranean location with international reach.",
    location: "Gibraltar, Gibraltar", type: "fight",
  },
  {
    title: "Singapore Fight Night",
    country: "Singapore", city: "Singapore", sport: "Boxing",
    weightClass: "Flyweight", level: "Professional",
    purse: "€10,000", travelIncluded: true, accommodationIncluded: true,
    status: "expected",
    description: "Flyweight professional boxing night in Singapore. Expected opening for IFA fighters in the Asian circuit.",
    location: "Singapore, Singapore", type: "fight",
  },
  {
    title: "Manila Boxing Showcase",
    country: "Philippines", city: "Manila", sport: "Boxing",
    weightClass: "Bantamweight", level: "Professional",
    purse: "€9,500", travelIncluded: true, accommodationIncluded: true,
    status: "recruiting",
    description: "Bantamweight boxing showcase in Manila. IFA is recruiting fighters for this Southeast Asian market event.",
    location: "Manila, Philippines", type: "fight",
  },
  {
    title: "Jakarta International Card",
    country: "Indonesia", city: "Jakarta", sport: "Boxing",
    weightClass: "Lightweight", level: "Professional",
    purse: "€8,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Lightweight international card in Jakarta. Rapidly growing market with strong local interest.",
    location: "Jakarta, Indonesia", type: "fight",
  },
  {
    title: "Bali Combat Sports Showcase",
    country: "Indonesia", city: "Bali", sport: "Boxing",
    weightClass: "Welterweight", level: "Professional",
    purse: "€6,000", travelIncluded: true, accommodationIncluded: true,
    status: "scouting",
    description: "Welterweight combat sports showcase in Bali. IFA is scouting for this premium Indonesian event.",
    location: "Bali, Indonesia", type: "fight",
  },
  {
    title: "Marbella Fight Night",
    country: "Spain", city: "Marbella", sport: "Boxing",
    weightClass: "Middleweight", level: "Professional",
    purse: "€9,000", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Middleweight boxing night in Marbella. Premium Mediterranean venue with European and international audience.",
    location: "Marbella, Spain", type: "fight",
  },
  {
    title: "Lisbon Boxing Opportunity",
    country: "Portugal", city: "Lisbon", sport: "Boxing",
    weightClass: "Super Lightweight", level: "Professional",
    purse: "€6,500", travelIncluded: true, accommodationIncluded: true,
    status: "open",
    description: "Super lightweight boxing opportunity in Lisbon. Growing European market with broadcast and media support.",
    location: "Lisbon, Portugal", type: "fight",
  },
  {
    title: "Dublin Boxing Card",
    country: "Ireland", city: "Dublin", sport: "Boxing",
    weightClass: "Featherweight", level: "Professional",
    purse: "€7,500", travelIncluded: true, accommodationIncluded: true,
    status: "recruiting",
    description: "Featherweight boxing card in Dublin. IFA is recruiting fighters for this passionate Irish boxing event.",
    location: "Dublin, Ireland", type: "fight",
  },
  {
    title: "Copenhagen Fight Opportunity",
    country: "Denmark", city: "Copenhagen", sport: "Boxing",
    weightClass: "Cruiserweight", level: "Professional",
    purse: "€14,000", travelIncluded: true, accommodationIncluded: true,
    status: "expected",
    description: "Cruiserweight fight opportunity in Copenhagen. Expected to open for IFA registered fighters.",
    location: "Copenhagen, Denmark", type: "fight",
  },
  {
    title: "Stockholm Boxing Showcase",
    country: "Sweden", city: "Stockholm", sport: "Boxing",
    weightClass: "Light Heavyweight", level: "Professional",
    purse: "€16,000", travelIncluded: true, accommodationIncluded: true,
    status: "scouting",
    description: "Light heavyweight boxing showcase in Stockholm. IFA is scouting Nordic and international fighters.",
    location: "Stockholm, Sweden", type: "fight",
  },
  {
    title: "Kuwait City Boxing Opportunity",
    country: "Kuwait", city: "Kuwait City", sport: "Boxing",
    weightClass: "Heavyweight", level: "Professional",
    purse: "€55,000", travelIncluded: true, accommodationIncluded: true,
    status: "recruiting",
    description: "Major heavyweight opportunity in Kuwait City. IFA is actively recruiting for this high-purse Gulf event.",
    location: "Kuwait City, Kuwait", type: "fight",
  },
];

async function seed() {
  console.log("Clearing existing fight opportunities...");
  // We only clear type=fight rows to preserve sponsors
  const existing = await db.select().from(opportunitiesTable);
  const fightIds = existing.filter(o => o.type === "fight").map(o => o.id);
  if (fightIds.length > 0) {
    const { inArray } = await import("drizzle-orm");
    await db.delete(opportunitiesTable).where(inArray(opportunitiesTable.id, fightIds));
  }

  console.log(`Inserting ${past.length} past opportunities...`);
  for (const opp of past) {
    await db.insert(opportunitiesTable).values(opp as any);
  }

  console.log(`Inserting ${upcoming.length} upcoming opportunities...`);
  for (const opp of upcoming) {
    await db.insert(opportunitiesTable).values(opp as any);
  }

  console.log("Done. Total inserted:", past.length + upcoming.length);
  process.exit(0);
}

seed().catch(err => {
  console.error(err);
  process.exit(1);
});
